# Generated by Django 3.0.8 on 2020-09-13 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('added_time', models.DateTimeField(default=datetime.datetime(2020, 9, 13, 21, 16, 58, 819395, tzinfo=utc))),
                ('remaining_days', models.IntegerField(default=1)),
            ],
        ),
    ]
