# Generated by Django 3.0.8 on 2020-09-21 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='remaining_days',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
